cutoff_len: 1024
dataset: QuestionTest
dataset_dir: data
do_train: true
eval_steps: 100
evaluation_strategy: steps
finetuning_type: lora
flash_attn: auto
fp16: true
gradient_accumulation_steps: 8
learning_rate: 5.0e-05
load_best_model_at_end: true
logging_steps: 5
lora_alpha: 16
lora_dropout: 0
lora_rank: 8
lora_target: q_proj,v_proj
lr_scheduler_type: cosine
max_grad_norm: 1.0
max_samples: 100000
model_name_or_path: Qwen/Qwen1.5-0.5B
num_train_epochs: 3.0
optim: adamw_torch
output_dir: saves\Qwen1.5-0.5B\lora\train_2024-05-18-22-00-35
packing: false
per_device_eval_batch_size: 1
per_device_train_batch_size: 1
plot_loss: true
preprocessing_num_workers: 16
quantization_bit: 4
report_to: none
save_steps: 100
stage: sft
template: default
val_size: 0.2
warmup_steps: 0
