adapter_name_or_path: saves\ChineseLLaMA2-1.3B\lora\train_2024-05-19-19-22-13
cutoff_len: 1024
dataset: QT2_2
dataset_dir: data
do_predict: true
finetuning_type: lora
flash_attn: fa2
max_new_tokens: 512
max_samples: 100000
model_name_or_path: hfl/chinese-llama-2-1.3b
output_dir: saves\ChineseLLaMA2-1.3B\lora\eval_2024-05-19-19-22-13
per_device_eval_batch_size: 2
predict_with_generate: true
preprocessing_num_workers: 16
quantization_bit: 4
stage: sft
temperature: 0.95
template: default
top_p: 0.5
