adapter_name_or_path: saves\Qwen1.5-0.5B\lora\train_2024-05-18-22-00-35
cutoff_len: 1024
dataset: QT2_2
dataset_dir: data
do_predict: true
finetuning_type: lora
flash_attn: auto
max_new_tokens: 512
max_samples: 100000
model_name_or_path: Qwen/Qwen1.5-0.5B
output_dir: saves\Qwen1.5-0.5B\lora\eval_2024-05-19-18-53-21
per_device_eval_batch_size: 1
predict_with_generate: true
preprocessing_num_workers: 16
quantization_bit: 4
stage: sft
temperature: 0.95
template: default
top_p: 0.7
