adapter_name_or_path: saves\Gemma-2B\lora\train_2024-05-20-23-44-24
cutoff_len: 1024
dataset: QT2_2
dataset_dir: data
do_predict: true
finetuning_type: lora
flash_attn: fa2
max_new_tokens: 512
max_samples: 100000
model_name_or_path: google/gemma-2b
output_dir: saves\Gemma-2B\lora\eval_2024-05-21-09-22-53
per_device_eval_batch_size: 2
predict_with_generate: true
preprocessing_num_workers: 16
quantization_bit: 4
stage: sft
temperature: 0.95
template: default
top_p: 0.7
